name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Find GOPATH location
        id: gopath
        run: echo "::set-output name=dir::$(go env GOPATH)"

      - name: Find GOCACHE location
        id: gocache
        run: echo "::set-output name=dir::$(go env GOCACHE)"

      - name: Cache GOPATH folder
        uses: actions/cache@v4
        with:
          path: ${{ steps.gopath.outputs.dir }}
          key: ${{ runner.os }}-gopath-${{ hashFiles(format('{0}{1}', github.workspace, '/go.sum')) }}
          restore-keys: |
            ${{ runner.os }}-gopath-

      - name: Cache GOCACHE folder
        uses: actions/cache@v4
        with:
          path: ${{ steps.gocache.outputs.dir }}
          key: ${{ runner.os }}-gocache-${{ hashFiles(format('{0}{1}', github.workspace, '/go.sum')) }}
          restore-keys: |
            ${{ runner.os }}-gocache-

      - name: Install dependencies
        run: |
          go get ./...

      - name: Run Tests
        run: |
          go test ./...
